### PR TITLE
Added instructions for unpacking LS jar, improving startup times

### PR DESCRIPTION
**Pull request by chorsley**

### CODE REVIEW

**Comment by nikolavp** [comment]
I can confirm that this makes the startup time on my machine much better. And I had a problems with _unicode.data_ not found with the flat jar(I think there is an issue for this in jira)

Best, Nikola

**Comment by garlandkr** [comment]
time java -jar logstash.jar -V
real    0m23.443s user    0m26.130s sys     0m2.448s

time java -cp logstash logstash.runner -V
real    0m5.196s user    0m8.077s sys     0m0.904s

This seems trivial though, since it is only the initial startup. If it made a difference during runtime it would certainly be worth investigating.

**Comment by chorsley** [comment]
@garlandkr That might be worth noting. It may not be much advantage to a production system, but for testing a new config when you're constantly restarting logstash, it's very handy to speed up the startup.

**Comment by garlandkr** [comment]
@chorsley fair point, it does take long enough to be irritating during development. I'll be implementing this when doing so, thanks!

**Comment by jordansissel** [comment]
It is my preference that this (older) solution be deprecated in favor of using the new 'flatjar'  documented here: http://cookbook.logstash.net/recipes/faster-startup-time/

The only impact with either of these solutions is a faster startup time.

**Comment by jordansissel** [comment]
The 'unicode.data' problem should get fixed in the next week or so, fwiw.

**Comment by chorsley** [comment]
@jordansissel I'll respect your judgement here of going with "flatjar" and leaving things as is. I'll close this pull request.

**Comment by jordansissel** [comment]
@chorsley Make you a deal - since this pull is closed, I'll fix the flatjar problems tonight if I can! :)

**Comment by chorsley** [comment]
@jordansissel Excellent, looking forward to giving it a try :)

**Pull request closed without merging**
