### PR TITLE
add Chef recipe

### PR DESCRIPTION
**Pull request by bryanwb**

### CODE REVIEW

**Comment by jordansissel** [comment]
Thanks! :)

**Comment by bryanwb** [comment]
hey @jordansissel, i don't see the new recipe on http://cookbook.logstash.net  .  Did I forget something?

**Comment by jordansissel** [comment]
nah, I haven't setup a cron job yet to rebuild the site automatically. Building now; should be live in a few seconds.

**Comment by bryanwb** [comment]
tks,

sorry to bother, i assumed it was my mistake

**Comment by jordansissel** [comment]
no worries :)

**Comment by bryanwb** [comment]
hey @jordansissel just fyi, i still don't see the cookbook listed on http://cookbook.logstash.net

**Comment by jordansissel** [comment]
doh; buiding the site now. I"ll make a cronjob do this eventually ;)

**Pull request merged**
