### PR TITLE
Add init script to manage logstash as a service under RHEL.

### PR DESCRIPTION
**Pull request by augieschwer**
The following change adds an init script that can be placed under /etc/init.d/ and can be managed by chkconfig and service to better integrate logstash into a RHEL based server.

### CODE REVIEW

**Comment by ghost** [comment]
Hi :-)

I don't think it's a good idea to add a single init script, because there are lots of git repositories with ready made scripts and configuration files for logstash.

It should be better to create a list of available repositories, analog to the list of available log-shippers.

Cheers

**Comment by ghost** [comment]
And the init script honestly sucks. There is no sysconfig/logstash to include and overwrite configs. The set_pidfile function returns more than one pid. The usage of the variable JAVAMEM makes no sense. There should be two variables like JAVA_MIN_MEM and JAVA_MAX_MEM for Xms and Xmx. ;-)

**Comment by jordansissel** [comment]
@bloonix: "sysconfig" is a redhat thing only, most other distros that support sysv init do not have /etc/sysconfig anyway.

**Comment by ghost** [comment]
Yes, sysconfig is a redhat thing. The subject of the pull request is "Add init script to manage logstash as a service under RHEL." and I think RHEL means redhat. In this case it would be nice to have /etc/sysconfig/logstash to overwrite variables instead to edit the init script. Cheers :-)

**Pull request merged**
